#include <stdio.h>
#include <stdlib.h>
void main(){ 
  int vet[10], *p1, x, y;
  for(x = 0; x < 10; x++ )     // ............................. 
   *( vet + x ) = x;           // .............................  

  // scambio tra variabili
  x = 33;
  p1 = &x; 		  		// ............................. 
  y = *p1;			    // ............................. 
  printf("valore di x , y , p1: %d %d 0x%X\n", x, y, p1);

  // operazioni coi vettori 
  *p1 = 0;		  		// ............................. 
  p1 = &vet[0];	  		// ............................. 
  p1 = &vet[1];	  		// ............................. 
  printf("valore di p1 e *p1  0x%X %d\n", p1, *p1);
  *p1 = *p1 + 7;  		// ............................. 
  printf("valore di p1 e *p1  0x%X %d\n", p1, *p1);
  (*p1)++;		  		// ............................. 
                        // ............................. 
  printf("valore di p1 e *p1  0x%X %d\n", p1, *p1);
                        
  p1 = vet;		  		// ............................. 
  *(p1 + 5);			// ............................. 
  printf("valore di p1 e *p1  0x%X %d\n", p1, *p1);
  printf("valore di *(p1 + 5) %d\n", *(p1 + 5));

  // operazione nelle matrici 
  int mat[2][3]; 
  for(x = 0; x < 2; x++ )      // .............................  
   for(y = 0; y < 3; y++ )       
     mat[x][y] = x + y;
 
  int *p2;
  p2 = mat + 1; 		// ............................. 
  *(p2 + 2);		    // ............................. 
  printf("valore di p2 e *p2  0x%X %d\n", p2, *p2);
  printf("valore di *(p2 + 2) %d\n", *(p2 + 2));
}


/* Time-stamp: "2014-09-06 03:26:06 paolo"    */
/* Scopo: esercizi                           */ 
/* HOEPLI - Informatica in C e C++ - 2016     */

